### PR TITLE
Add CircleCI

### PR DESCRIPTION
**Pull request by jmini**
This PR adds a CircleCI config to test this project.

---
Tested with the [`circleci`](https://github.com/jmini/quarkus-todo-app/tree/circleci) branch in my repo:

* https://github.com/jmini/quarkus-todo-app/commit/3da51bfb8ceb10ab0b7a81b6ec3f6678a792184b produces a test error ([Job 2](https://circleci.com/gh/jmini/quarkus-todo-app/2))
* https://github.com/jmini/quarkus-todo-app/commit/c04a52a98c8576956964d194cf1903e648a534d9 fixes the error ([Job 2](https://circleci.com/gh/jmini/quarkus-todo-app/3))

Job 2 screenshot:
Screenshot 2019-07-07 at 17 00 17

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Comment by jmini** [comment]
You need to activate CircleCI on your project.

For the moment, the Badge URL:
```
https://circleci.com/gh/cescoffier/quarkus-todo-app.svg?style=svg
```
returns "NO BUILD"

**Comment by cescoffier** [comment]
Fixed, sorry, I was on my phone so not the best to login to circleci (I never used it before).

Can you open a PR to add the badge to the readme?

**Comment by jmini** [comment]
> Can you open a PR to add the badge to the readme?

Yes (it was already on my list): https://github.com/cescoffier/quarkus-todo-app/pull/5

**Pull request merged**
